#!/usr/bin/env bash

# Changes the following domain resolve IPs:
#   localhost from 127.0.0.1 to 127.0.0.2
#   facebook.com from 157.240.11.35 to 8.8.8.8

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Modify the hosts file
sudo sed -i 's/^127\.0\.0\.1.*localhost$/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/^157\.240\.11\.35.*facebook\.com$/8.8.8.8 facebook.com/' /etc/hosts

