#!/usr/bin/env bash
# Fixing the web server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
